name: Close Pull Request

on:
  pull_request_target:
    branches: [crux]
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "VyOS 1.2 (crux) is end-of-life. Please upgrade to 1.3 (equuleus) or later"
